services:
  product-service:
    build: ./src/ProductService/
    container_name: product-service
    depends_on:
      - sql-server
      - nginx
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    ports:
      - 5001:80
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=A&VeryComplex123Password
    volumes:
      - sql-server-volume:/var/opt/mssql
  nginx:
    build: ./src/nginx/
    container_name: nginx
    ports:
      - 5000:80
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
  basket-service:
    build: ./src/BasketService/
    container_name: basket-service
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    restart: always
    depends_on:
      - redis
      - nginx
    ports:
      - 5002:80
    
volumes:
  sql-server-volume:
  redis-data: