services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1tsJusT@S@mpleP@ssword!
    volumes:
      - sql-server-data:/var/opt/mssql
    networks:
      - net
  nginx:
    build: ./src/Nginx/
    container_name: nginx
    ports:
      - 5000:80
    networks:
      - net
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - net
  seq:
    image: datalust/seq
    container_name: seq
    ports:
      - 5431:80
    volumes:
      - seq-data:/data
    environment:
      - ACCEPT_EULA=Y
    networks:
      - net
  frontend:
    build: ./src/Frontend
    image: notilya4/frontend
    container_name: frontend
    ports:
      - 4200:80
    networks:
      - net
    
volumes:
  sql-server-data:
  redis-data:
  seq-data:

networks:
  net:
    name: yet-another-marketplace-network
    driver: bridge