services:
  product-service:
    build: ./src/ProductService/
    image: notilya4/yet-another-marketplace.product-service
    container_name: product-service
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    depends_on:
      - sql-server
      - seq
  account-service:
    build: ./src/AccountService/
    image: notilya4/yet-another-marketplace.account-service
    container_name: account-service
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    depends_on:
      - sql-server
      - redis
      - seq
  gateway:
    build: ./src/Gateway/
    image: notilya4/yet-another-marketplace.gateway
    container_name: gateway
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    depends_on:
      - account-service
      - basket-service
      - product-service
    ports:
      - 5003:80
  basket-service:
    build: ./src/BasketService/
    image: notilya4/yet-another-marketplace.basket-service
    container_name: basket-service
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    depends_on:
      - redis
      - seq
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1tsJusT@S@mpleP@ssword!
    volumes:
      - sql-server-data:/var/opt/mssql
  nginx:
    build: ./src/Nginx/
    container_name: nginx
    ports:
      - 5000:80
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
  seq:
    image: datalust/seq
    container_name: seq
    ports:
      - 5341:80
    volumes:
      - seq-data:/data
    environment:
      - ACCEPT_EULA=Y
  frontend:
    build: ./src/Frontend
    image: notilya4/yet-another-marketplace.frontend
    container_name: frontend
    ports:
      - 4200:80
    
volumes:
  sql-server-data:
  redis-data:
  seq-data: